### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by ernestoongaro** [aldadic/home-assistant-on-echo-show#2]
Just following the installation instruction, and I don't see anything about authentication.

I assume [someToken](https://github.com/aldadic/home-assistant-on-echo-show/blob/a8652ead7676bfb802ec21f23e3435e715918154/lambda_function.py#L21) in `lambda_function.py` should be replaced with a [long lived access token](https://developers.home-assistant.io/docs/auth_api/#long-lived-access-token)?

**Comment by aldadic** [comment]
You are right, there is no authentication. This skill just opens Home Assistant in the built-in browser on the Echo Show. Like on any other device, you will first need to login using your username and password. Don't forget to select the "keep me logged in" option so that you won't need to do this again.

**Comment by ernestoongaro** [comment]
Ah ok! Thank you for the clarification, and awesome work here :)

**Comment by JoernBerkefeld** [comment]
somehow im getting website not available and the question if i might have a typo in the url. any thoughts?
I do not ssl or access from the outside enabled but my echos and HA are in the same network. trying the very same url on my laptop leads me to the login prompt :(
means the url is right but somehow my echo cannot open it / reach it?

**Comment by ernestoongaro** [comment]
For me the .local domain didn’t work, had to use .lan from echo

Try loading in the browser (silk) first
